[package]
name = "ohcrab"
version = "0.1.0"
edition = "2021"
description = "Fix your command line magically"
authors = ["Luiz Otavio Vilas Boas Oliveira <luiz.vbo@gmail.com>"]

[dependencies]
clap = { version = "4.2.2", features = ["derive", "cargo", "env"] }
thiserror = "1.0.40"
shellwords = "1.1.0"
which = "4.4.0"
