[package]
name = "ohcrab"
version = "0.1.0"
edition = "2021"
description = "Fix your command line magically"
authors = ["Luiz Otavio Vilas Boas Oliveira <luiz.vbo@gmail.com>"]
license = "MIT"
repository = "https://github.com/luizvbo/oh-crab"
readme = "README.md"
keywords = ["fix", "command", "terminal"]
categories = ["command-line-utilities"]
msrv = "1.70.0"

[dependencies]
clap = { version = "4.2.2", features = ["derive", "cargo", "env"] }
shellwords = "1.1.0"
which = "4.4.0"
similar = "2.2.1"
console = "0.15.7"
log = "0.4.20"
env_logger = "0.10.0"
