name: CI

on:
  push:
    branches: [main, master]
    paths-ignore:
      - "README.md"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Install Rust toolchain"
        run: rustup component add rustfmt clippy
      - name: "Check formatting"
        run: cargo fmt --all --check
      - name: "Run Clippy"
        run: cargo clippy --workspace --all-targets --all-features --locked -- -D warnings

  test-linux:
    name: "Test | Ubuntu"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rui314/setup-mold@v1
      - uses: Swatinem/rust-cache@v2
      - name: "Install cargo-nextest"
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest
      - name: "Run tests"
        run: cargo nextest run --workspace --no-fail-fast

  test-macos:
    name: "Test | macOS"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: "Install cargo-nextest"
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest
      - name: "Run tests"
        run: cargo nextest run --workspace --no-fail-fast

  test-windows:
    name: "Test | Windows"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Create Dev Drive"
        run: ./.github/workflows/setup-dev-drive.ps1
        shell: powershell
      - uses: Swatinem/rust-cache@v2
      - name: "Install cargo-nextest"
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest
      - name: "Run tests"
        run: cargo nextest run --workspace --no-fail-fast
