name: "Publish"

on:
  workflow_call:
    inputs:
      plan:
        required: true
        type: string

jobs:
  crates-io:
    name: "Upload to crates.io"
    runs-on: ubuntu-latest
    environment:
      name: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: "Install Rust"
        uses: dtolnay/rust-toolchain@stable
      - name: "Download crate"
        uses: actions/download-artifact@v4
        with:
          pattern: artifacts-*.crate
          path: crate
      - name: "Publish to crates.io"
        run: cargo publish --token ${{ secrets.CRATES_IO_API_TOKEN }} --allow-dirty --no-verify crate/*.crate
